export const dataList={
    symptomList:[   {"id": "1", "name": "Neck pain / HWS"},
    {"id": "2", "name": "Headaches / Kopfschmerzen"},
    {"id": "3", "name": "Migraine"},
    {"id": "4", "name": "Dizziness / Schwindel"},
    {"id": "5", "name": "Tinnitus / Tinitus"},
    {"id": "6", "name": "TMJ / CMD"},
    {"id": "7", "name": "Shoulder Pain / Schulterschmerzen"},
    {"id": "8", "name": "Elbow Pain / Ellebogeschmerzen"},
    {"id": "9", "name": "Wrist Pain / Schmerzen der Handgelenk"},
    {"id": "10", "name": "Thoracic Spine Pain /BWS"},
    {"id": "11", "name": "Chest Pain / Brustschmerzen"},
    {"id": "12", "name": "Lumbago / LWS"},
    {"id": "13", "name": "Acute Low Back / Hexenschuss"},
    {"id": "14", "name": "Sciatica / Ischiasschmerzen"},
    {"id": "15", "name": "SI Joint Pain / Ischiasschmerzen"},
    {"id": "16", "name": "Hip Pain / Hüfteschmerzen"},
    {"id": "17", "name": "Leg Pain /Oberschenkel Schmerzen"},
    {"id": "18", "name": "Knee Pain / Knieschmerzen"},
    {"id": "19", "name": "Calf Pain / Unterschenkel-Warde(n)"},
    {"id": "20", "name": "Heel Pain / Fersenschmerzen"},
    {"id": "21", "name": "Foot Pain / Füß Schmerzen"},
    {"id": "22", "name": "Scoliosis / Skoliose"}],
    radiatesList:[ {"id": "1", "name": "Head"}, 
    {"id": "2", "name": "Shoulder"}, 
    {"id": "3", "name": "Upper Arm"}, 
    {"id": "4", "name": "Lower Arm"}, 
    {"id": "5", "name": "Hand - fingers"}, 
    {"id": "6", "name": "Fingers 1,2,3"}, 
    {"id": "7", "name": "Fingers 3,4,5"}, 
    {"id": "8", "name": "Upper back"}, 
    {"id": "9", "name": "Shoulder blades"}, 
    {"id": "10", "name": "Chest"}, 
    {"id": "11", "name": "Low back"}, 
    {"id": "12", "name": "Si Joint"}, 
    {"id": "13", "name": "Buttocks"}, 
    {"id": "14", "name": "From Buttocks to foot/feet"}, 
    {"id": "15", "name": "Posterior Thigh"}, 
    {"id": "16", "name": "Anterior Thigh"}, 
    {"id": "17", "name": "Lateral high"}, 
    {"id": "18", "name": "Knee front"}, 
    {"id": "19", "name": "Knee lateral"}, 
    {"id": "20", "name": "Knee medial"}, 
    {"id": "21", "name": "Knee posterior"}, 
    {"id": "22", "name": "Calf"} ],
    describeSymptomsList:[{"id": "1", "name": "an ache"}, 
    {"id": "2", "name": "sharp"}, 
    {"id": "3", "name": "dull"}, 
    {"id": "4", "name": "shooting"}, 
    {"id": "5", "name": "tingling"}, 
    {"id": "6", "name": "numb"}, 
    {"id": "7", "name": "burning"}, 
    {"id": "8", "name": "sensitive"}, 
    {"id": "9", "name": "sore"}],
    onSetList:[ {"id": "1", "name": "Injury"}, 
    {"id": "2", "name": "Accident"}, 
    {"id": "3", "name": "Insidious"}],
    palliativeList:[{"id": "1", "name": "Sports"}, 
    {"id": "2", "name": "Walking"}, 
    {"id": "3", "name": "Working"}, 
    {"id": "4", "name": "Running"}, 
    {"id": "5", "name": "Lifting"}, 
    {"id": "6", "name": "Sitting"}, 
    {"id": "7", "name": "Lying Down"}, 
    {"id": "8", "name": "Rest"} ],
    provocativeList:[ {"id": "1", "name": "Sports"}, 
    {"id": "2", "name": "Walking"}, 
    {"id": "3", "name": "Working"}, 
    {"id": "4", "name": "Running"}, 
    {"id": "5", "name": "Lifting"}, 
    {"id": "6", "name": "Sitting"}, 
    {"id": "7", "name": "Lying Down"}, 
    {"id": "8", "name": "Rest"} ],
    warningsList:[{"id": "1", "name": "No Cervical Manual!"}, 
    {"id": "2", "name": "Osteoporosis"}, 
    {"id": "3", "name": "Disc Herniation - Use Disc Protocols"}, 
    {"id": "4", "name": "Scoliosis"} ],
    therapistList:[{"id": "1", "name": "Family Doctor / Hausarzt"}, 
    {"id": "2", "name": "Orthopedist"}, 
    {"id": "3", "name": "Osteopath"}, 
    {"id": "4", "name": "Chiropractor"}, 
    {"id": "5", "name": "Heiplraktiker"}, 
    {"id": "6", "name": "Physiotherapeut"}, 
    {"id": "7", "name": "Surgeon"}, 
    {"id": "8", "name": "Massage Therapeut"}, 
    {"id": "9", "name": "Psychologe"}, 
    {"id": "10", "name": "Andere"}],
    helpList:[ {"id": "1", "name": "Yes"}, 
    {"id": "2", "name": "No"}, 
    {"id": "3", "name": "A little"},
    {"id": "4", "name": "A lot"}]
}